import { useState, useEffect } from 'react';
import {
  Smartphone, FolderOpen, MessageSquare, Clock, Trash2, ArrowRight,
  Layers, Zap, Globe, Sparkles, ChevronRight,
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';

interface ChatSession {
  id:        string;
  title:     string;
  createdAt: string;
  updatedAt: string;
  pipeline?: 'web' | 'webapp';
}

const SESSIONS_KEY = 'n8n-webapp-sessions-v1';

function timeAgo(ts: string) {
  const diff = Date.now() - new Date(ts).getTime();
  const m = Math.floor(diff / 60000);
  if (m < 1) return 'just now';
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  return `${Math.floor(h / 24)}d ago`;
}

function loadSessions(): ChatSession[] {
  try {
    const all: ChatSession[] = JSON.parse(localStorage.getItem(SESSIONS_KEY) || '[]');
    return all.filter(s => (s.pipeline ?? 'webapp') === 'webapp');
  } catch { return []; }
}

function msgCount(sessionId: string): number {
  try {
    const msgs = JSON.parse(localStorage.getItem(`n8n-msgs-${sessionId}`) || '[]');
    return Array.isArray(msgs) ? msgs.length : 0;
  } catch { return 0; }
}

export default function MobileProjectsPage() {
  const navigate = useNavigate();
  const [sessions, setSessions] = useState<ChatSession[]>([]);

  useEffect(() => { setSessions(loadSessions()); }, []);

  const deleteSession = (id: string) => {
    const updated = sessions.filter(s => s.id !== id);
    setSessions(updated);
    localStorage.setItem(SESSIONS_KEY, JSON.stringify(updated));
    localStorage.removeItem(`n8n-msgs-${id}`);
    localStorage.removeItem(`n8n-building-${id}`);
  };

  const totalMessages = sessions.reduce((acc, s) => acc + msgCount(s.id), 0);

  return (
    <div className="page-body" style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>

      {/* ── Hero header ──────────────────────────────────────────────────── */}
      <div style={{
        background: 'linear-gradient(135deg, rgba(139,92,246,0.08) 0%, rgba(96,165,250,0.07) 60%, rgba(45,212,191,0.05) 100%)',
        border: '1px solid rgba(139,92,246,0.18)',
        borderRadius: 'var(--radius-lg, 14px)',
        padding: '1.375rem 1.625rem',
        display: 'flex', alignItems: 'center', gap: '1rem',
        position: 'relative', overflow: 'hidden',
      }}>
        {/* Glow */}
        <div style={{
          position: 'absolute', top: -50, right: -50, width: 200, height: 200,
          background: 'radial-gradient(circle, rgba(139,92,246,0.12) 0%, transparent 70%)',
          pointerEvents: 'none',
        }} />

        <div style={{
          width: 52, height: 52, borderRadius: '14px', flexShrink: 0,
          background: 'linear-gradient(135deg, #a78bfa, #60a5fa)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          boxShadow: '0 4px 20px rgba(167,139,250,0.3)',
        }}>
          <Smartphone size={24} color="#fff" />
        </div>

        <div style={{ flex: 1 }}>
          <h1 style={{
            margin: 0, fontSize: '1.125rem', fontWeight: 800,
            color: 'var(--text-primary)', letterSpacing: '-0.02em',
          }}>
            Website + Mobile App Projects
          </h1>
          <p style={{ margin: '0.2rem 0 0', fontSize: '0.8rem', color: 'var(--text-secondary)', lineHeight: 1.5 }}>
            Full-stack projects generated by the Website &amp; Mobile App AI pipeline.
            {sessions.length > 0 && ` ${sessions.length} project${sessions.length !== 1 ? 's' : ''} saved locally.`}
          </p>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', flexShrink: 0 }}>
          {sessions.length > 0 && (
            <div style={{
              display: 'flex', gap: '1.25rem',
              padding: '0.5rem 1rem',
              background: 'rgba(255,255,255,0.04)',
              borderRadius: 'var(--radius-md)',
              border: '1px solid var(--border)',
            }}>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '1.25rem', fontWeight: 800, color: '#a78bfa', lineHeight: 1 }}>{sessions.length}</div>
                <div style={{ fontSize: '0.6rem', color: 'var(--text-muted)', marginTop: '2px', textTransform: 'uppercase', letterSpacing: '0.07em' }}>Projects</div>
              </div>
              <div style={{ width: 1, background: 'var(--border)' }} />
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: '1.25rem', fontWeight: 800, color: 'var(--accent-blue)', lineHeight: 1 }}>{totalMessages}</div>
                <div style={{ fontSize: '0.6rem', color: 'var(--text-muted)', marginTop: '2px', textTransform: 'uppercase', letterSpacing: '0.07em' }}>Messages</div>
              </div>
            </div>
          )}
          <button
            className="btn btn-primary btn-sm"
            onClick={() => navigate('/chat-webapp')}
            style={{ gap: '0.4rem', whiteSpace: 'nowrap' }}
          >
            <MessageSquare size={13} /> New Project
          </button>
        </div>
      </div>

      {/* ── Pipeline info chips ───────────────────────────────────────────── */}
      <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
        {[
          { icon: <Globe size={11} />,       label: 'React Website',       color: 'rgba(96,165,250,0.1)',   border: 'rgba(96,165,250,0.2)',   text: 'var(--accent-blue)'    },
          { icon: <Smartphone size={11} />,  label: 'React Native App',    color: 'rgba(167,139,250,0.1)', border: 'rgba(167,139,250,0.2)', text: '#a78bfa'               },
          { icon: <Layers size={11} />,      label: 'n8n AI Workflow',     color: 'rgba(45,212,191,0.08)', border: 'rgba(45,212,191,0.18)', text: 'var(--accent-teal)'    },
          { icon: <FolderOpen size={11} />,  label: 'NAS file storage',    color: 'rgba(251,146,60,0.08)', border: 'rgba(251,146,60,0.2)',  text: 'var(--accent-orange)'  },
        ].map((chip, i) => (
          <span key={i} style={{
            display: 'flex', alignItems: 'center', gap: '0.35rem',
            padding: '0.3rem 0.7rem', borderRadius: '999px',
            background: chip.color, border: `1px solid ${chip.border}`,
            fontSize: '0.7rem', fontWeight: 600, color: chip.text,
          }}>
            {chip.icon} {chip.label}
          </span>
        ))}
      </div>

      {/* ── Project list ──────────────────────────────────────────────────── */}
      {sessions.length > 0 ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.625rem' }}>
          {sessions.map((s, idx) => {
            const msgs    = msgCount(s.id);
            const isNew   = s.title === 'New Project';
            return (
              <div
                key={s.id}
                onClick={() => navigate('/chat-webapp')}
                style={{
                  background: 'var(--bg-card)', border: '1px solid var(--border)',
                  borderRadius: 'var(--radius-md)',
                  display: 'flex', alignItems: 'center', gap: '1rem',
                  padding: '1rem 1.25rem',
                  cursor: 'pointer',
                  transition: 'border-color 0.2s, box-shadow 0.2s, transform 0.15s',
                  animation: `fadeUp 0.2s ease ${idx * 0.04}s both`,
                }}
                onMouseEnter={e => {
                  const el = e.currentTarget as HTMLDivElement;
                  el.style.borderColor = 'rgba(167,139,250,0.35)';
                  el.style.boxShadow   = '0 4px 20px rgba(167,139,250,0.1)';
                  el.style.transform   = 'translateY(-1px)';
                }}
                onMouseLeave={e => {
                  const el = e.currentTarget as HTMLDivElement;
                  el.style.borderColor = 'var(--border)';
                  el.style.boxShadow   = 'none';
                  el.style.transform   = 'translateY(0)';
                }}
              >
                {/* Project icon */}
                <div style={{
                  width: 42, height: 42, borderRadius: '11px', flexShrink: 0,
                  background: 'linear-gradient(135deg, rgba(167,139,250,0.15), rgba(96,165,250,0.1))',
                  border: '1px solid rgba(167,139,250,0.2)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                }}>
                  <Smartphone size={18} style={{ color: '#a78bfa' }} />
                </div>

                {/* Title + meta */}
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{
                    fontSize: '0.875rem', fontWeight: 600,
                    color: 'var(--text-primary)', whiteSpace: 'nowrap',
                    overflow: 'hidden', textOverflow: 'ellipsis',
                  }}>
                    {isNew ? <em style={{ color: 'var(--text-muted)', fontStyle: 'italic' }}>Untitled Project</em> : s.title}
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.625rem', marginTop: '0.25rem', flexWrap: 'wrap' }}>
                    <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '0.2rem' }}>
                      <Clock size={10} /> {timeAgo(s.createdAt)}
                    </span>
                    {s.updatedAt !== s.createdAt && (
                      <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>
                        · updated {timeAgo(s.updatedAt)}
                      </span>
                    )}
                    {msgs > 0 && (
                      <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '0.2rem' }}>
                        <MessageSquare size={10} /> {msgs} message{msgs !== 1 ? 's' : ''}
                      </span>
                    )}
                  </div>
                </div>

                {/* Pipeline badge */}
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '0.25rem', flexShrink: 0 }}>
                  <span style={{
                    fontSize: '0.62rem', fontWeight: 700,
                    padding: '0.2rem 0.55rem', borderRadius: '999px',
                    background: 'linear-gradient(90deg, rgba(167,139,250,0.12), rgba(96,165,250,0.12))',
                    border: '1px solid rgba(167,139,250,0.22)',
                    color: '#a78bfa',
                    display: 'flex', alignItems: 'center', gap: '0.3rem',
                  }}>
                    <Sparkles size={9} /> Website + App
                  </span>
                  <span style={{ fontSize: '0.65rem', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
                    NAS · mobile_*
                  </span>
                </div>

                {/* Actions */}
                <div
                  style={{ display: 'flex', alignItems: 'center', gap: '0.375rem', flexShrink: 0 }}
                  onClick={e => e.stopPropagation()}
                >
                  <button
                    className="btn btn-ghost btn-sm btn-icon"
                    title="Open in chat"
                    onClick={() => navigate('/chat-webapp')}
                    style={{ color: '#a78bfa' }}
                  >
                    <ArrowRight size={13} />
                  </button>
                  <button
                    className="btn btn-ghost btn-sm btn-icon"
                    title="Remove from list"
                    style={{ color: 'var(--accent-red)' }}
                    onClick={() => deleteSession(s.id)}
                  >
                    <Trash2 size={13} />
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      ) : (
        /* Empty state */
        <div style={{
          background: 'var(--bg-card)', border: '1px dashed rgba(167,139,250,0.25)',
          borderRadius: 'var(--radius-lg, 14px)',
          padding: '3.5rem 2rem', textAlign: 'center',
        }}>
          <div style={{
            width: 60, height: 60, borderRadius: '18px', margin: '0 auto 1.25rem',
            background: 'linear-gradient(135deg, rgba(167,139,250,0.12), rgba(96,165,250,0.08))',
            border: '1px solid rgba(167,139,250,0.2)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <Smartphone size={26} style={{ color: '#a78bfa' }} />
          </div>
          <div style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '0.5rem' }}>
            No projects yet
          </div>
          <div style={{ fontSize: '0.825rem', color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: '1.5rem', maxWidth: 400, margin: '0 auto 1.5rem' }}>
            Start a new chat in <strong>Website &amp; Mobile App</strong> to generate your first full-stack project.
            The AI will create both a website and a React Native app simultaneously.
          </div>
          <button
            className="btn btn-primary"
            onClick={() => navigate('/chat-webapp')}
            style={{
              gap: '0.5rem', padding: '0.7rem 1.75rem',
              background: 'linear-gradient(135deg, #a78bfa, #60a5fa)',
              boxShadow: '0 4px 20px rgba(167,139,250,0.25)',
            }}
          >
            <Zap size={15} /> Start a project <ChevronRight size={14} />
          </button>
        </div>
      )}

      {/* ── NAS footer note ───────────────────────────────────────────────── */}
      {sessions.length > 0 && (
        <div style={{
          display: 'flex', alignItems: 'center', gap: '0.625rem',
          padding: '0.7rem 1rem',
          background: 'rgba(45,212,191,0.04)',
          border: '1px solid rgba(45,212,191,0.12)',
          borderRadius: 'var(--radius-md)',
          fontSize: '0.72rem', color: 'var(--text-muted)',
        }}>
          <FolderOpen size={13} style={{ color: 'var(--accent-teal)', flexShrink: 0 }} />
          <span>
            Files saved on NAS at{' '}
            <code style={{ fontFamily: 'var(--font-mono)', color: 'var(--text-secondary)', fontSize: '0.7rem' }}>
              /n8n_data/Website &amp; Mobile App Generator/projects/&#123;username&#125;/
            </code>
            {' '}— open the{' '}
            <code style={{ fontFamily: 'var(--font-mono)', fontSize: '0.7rem' }}>mobile_*</code>
            {' '}folder in Cursor to run the app.
          </span>
        </div>
      )}

      <style>{`
        @keyframes fadeUp {
          from { opacity: 0; transform: translateY(6px); }
          to   { opacity: 1; transform: translateY(0);   }
        }
      `}</style>
    </div>
  );
}
